"""
Newton's Laws, a simulator of physics at the scale of space

Lists of textures for blobs, large and small

by Jason Mott, copyright 2024
"""

from newtons_blobs.globals import *

__author__ = "Jason Mott"
__copyright__ = "Copyright 2024"
__license__ = "GPL 3.0"
__version__ = VERSION
__maintainer__ = "Jason Mott"
__email__ = "github@jasonmott.com"
__status__ = "In Progress"


BLOB_TEXTURES_GAS = [
    # "textures/jupiter.jpg",
    # "textures/saturn.jpg",
    # "textures/neptune.jpg",
    # "textures/uranus.jpg",
    "textures/neptune_02.jpg",
    "textures/gas.jpg",
    "textures/space/solar_system_scope/8k_jupiter.jpg",
    "textures/space/solar_system_scope/8k_saturn.jpg",
    "textures/space/solar_system_scope/2k_neptune.jpg",
    "textures/space/solar_system_scope/2k_uranus.jpg",
    # "textures/gaseous/gaseous_01.png",
    "textures/gaseous/gaseous_02.png",
    # "textures/gaseous/gaseous_03.png",
    "textures/gaseous/gaseous_04.png",
    # "textures/gaseous/gaseous_05.png",
    "textures/gaseous/gaseous_06.png",
    # "textures/gaseous/gaseous_07.png",
    "textures/gaseous/gaseous_08.png",
    # "textures/gaseous/gaseous_09.png",
    "textures/gaseous/gaseous_10.png",
    # "textures/gaseous/gaseous_11.png",
    "textures/gaseous/gaseous_12.png",
    # "textures/gaseous/gaseous_13.png",
    "textures/gaseous/gaseous_14.png",
    # "textures/gaseous/gaseous_15.png",
    "textures/gaseous/gaseous_16.png",
    # "textures/gaseous/gaseous_17.png",
    "textures/gaseous/gaseous_18.png",
    # "textures/gaseous/gaseous_19.png",
    "textures/gaseous/gaseous_20.png",
    "textures/gas/gas_01.png",
    "textures/gas/gas_02.png",
    "textures/gas/gas_04.png",
    "textures/gas/gas_05.png",
    "textures/gas/gas_06.png",
    "textures/gas/gas_09.png",
    "textures/gas/gas_14.png",
    "textures/gas/gas_20.png",
]


BLOB_TEXTURES_ROCKY = [
    # "textures/sun03.png",
    # "textures/earth.jpg",
    # "textures/mercury.jpg",
    # "textures/venus.jpg",
    # "textures/mars.jpg",
    "textures/pluto.jpg",
    "textures/space/solar_system_scope/8k_earth_daymap.jpg",
    "textures/space/solar_system_scope/8k_mercury.jpg",
    "textures/space/solar_system_scope/4k_venus_atmosphere.jpg",
    "textures/space/solar_system_scope/8k_mars.jpg",
    # "textures/grassland/grassland_01.png",
    # "textures/grassland/grassland_02.png",
    # "textures/grassland/grassland_03.png",
    "textures/grassland/grassland_04.png",
    # "textures/grassland/grassland_05.png",
    # "textures/jungle/jungle_01.png",
    # "textures/jungle/jungle_02.png",
    # "textures/jungle/jungle_03.png",
    # "textures/jungle/jungle_04.png",
    "textures/jungle/jungle_05.png",
    # "textures/marshy/marshy_01.png",
    # "textures/marshy/marshy_02.png",
    # "textures/marshy/marshy_03.png",
    "textures/marshy/marshy_04.png",
    # "textures/marshy/marshy_05.png",
    "textures/martian/martian_01.png",
    # "textures/martian/martian_02.png",
    # "textures/martian/martian_03.png",
    # "textures/martian/martian_04.png",
    # "textures/martian/martian_05.png",
    # "textures/sandy/sandy_01.png",
    # "textures/sandy/sandy_02.png",
    "textures/sandy/sandy_03.png",
    # "textures/sandy/sandy_04.png",
    # "textures/sandy/sandy_05.png",
    "textures/snowy/snowy_01.png",
    # "textures/snowy/snowy_02.png",
    # "textures/snowy/snowy_03.png",
    # "textures/snowy/snowy_04.png",
    # "textures/snowy/snowy_05.png",
    # "textures/tundra/tundra_01.png",
    "textures/tundra/tundra_02.png",
    # "textures/tundra/tundra_03.png",
    # "textures/tundra/tundra_04.png",
    # "textures/tundra/tundra_05.png",
    "textures/alpine/alpine_20.png",
    "textures/fungal/fungal_13.png",
    "textures/ice/ice_03.png",
    "textures/mud/dry_mud_03.png",
    "textures/oasis/oasis_02.png",
    "textures/oceanic/oceanic_19.png",
    "textures/primordial/primordial_14.png",
    "textures/savannah/savannah_09.png",
    "textures/tundra02/tundral_14.png",
    "textures/earth_02.jpg",
    "textures/terraformed_mars.jpg",
    "textures/epsilon_eridani/epsilon_01.jpg",
    "textures/terrestrial/terrestrial_09.png",
]

BLOB_TEXTURES_MOON = [
    "textures/space/solar_system_scope/8k_moon.jpg",
    "textures/space/solar_system_scope/4k_ceres_fictional.jpg",
    "textures/space/solar_system_scope/4k_eris_fictional.jpg",
    "textures/space/solar_system_scope/4k_haumea_fictional.jpg",
    "textures/space/solar_system_scope/4k_makemake_fictional.jpg",
    "textures/space/solar_system_scope/8k_venus_surface.jpg",
    # "textures/arid/arid_01.png",
    # "textures/arid/arid_02.png",
    "textures/arid/arid_03.png",
    # "textures/arid/arid_04.png",
    # "textures/arid/arid_05.png",
    "textures/methane/methane_01.png",
    # "textures/methane/methane_02.png",
    # "textures/methane/methane_03.png",
    # "textures/methane/methane_04.png",
    # "textures/methane/methane_05.png",
    # "textures/barren/barren_01.png",
    "textures/barren/barren_02.png",
    # "textures/barren/barren_03.png",
    # "textures/barren/barren_04.png",
    # "textures/barren/barren_05.png",
    # "textures/dusty/dusty_01.png",
    "textures/dusty/dusty_02.png",
    # "textures/dusty/dusty_03.png",
    # "textures/dusty/dusty_04.png",
    # "textures/dusty/dusty_05.png",
    "textures/epsilon_eridani/epsilon_02.jpg",
    "textures/epsilon_eridani/epsilon_03.jpg",
    # "textures/epsilon_eridani/epsilon_04.jpg",
    # "textures/epsilon_eridani/epsilon_05.jpg",
    # "textures/epsilon_eridani/epsilon_06.jpg",
    # "textures/epsilon_eridani/epsilon_07.jpg",
    # "textures/epsilon_eridani/epsilon_08.jpg",
    "textures/rock/rock_17.png",
    # "textures/moon-1024-512.jpg",
    "textures/moon_01.png",
    "textures/moon_02.jpg",
    "textures/moon_03.jpg",
    "textures/moon_04.jpg",
    "textures/pluto.jpg",
]
