BLOB_TEXTURES_LARGE = [
    # "nb_ursina/textures/jupiter.jpg",
    # "nb_ursina/textures/saturn.jpg",
    # "nb_ursina/textures/neptune.jpg",
    # "nb_ursina/textures/uranus.jpg",
    "nb_ursina/textures/space/solar_system_scope/8k_jupiter.jpg",
    "nb_ursina/textures/space/solar_system_scope/8k_saturn.jpg",
    "nb_ursina/textures/space/solar_system_scope/2k_neptune.jpg",
    "nb_ursina/textures/space/solar_system_scope/2k_uranus.jpg",
    "nb_ursina/textures/gaseous/gaseous_01.png",
    "nb_ursina/textures/gaseous/gaseous_02.png",
    "nb_ursina/textures/gaseous/gaseous_03.png",
    "nb_ursina/textures/gaseous/gaseous_04.png",
    "nb_ursina/textures/gaseous/gaseous_05.png",
    "nb_ursina/textures/gaseous/gaseous_06.png",
    "nb_ursina/textures/gaseous/gaseous_07.png",
    "nb_ursina/textures/gaseous/gaseous_08.png",
    "nb_ursina/textures/gaseous/gaseous_09.png",
    "nb_ursina/textures/gaseous/gaseous_10.png",
    "nb_ursina/textures/gaseous/gaseous_11.png",
    "nb_ursina/textures/gaseous/gaseous_12.png",
    "nb_ursina/textures/gaseous/gaseous_13.png",
    "nb_ursina/textures/gaseous/gaseous_14.png",
    "nb_ursina/textures/gaseous/gaseous_15.png",
    "nb_ursina/textures/gaseous/gaseous_16.png",
    "nb_ursina/textures/gaseous/gaseous_17.png",
    "nb_ursina/textures/gaseous/gaseous_18.png",
    "nb_ursina/textures/gaseous/gaseous_19.png",
    "nb_ursina/textures/gaseous/gaseous_20.png",
]


BLOB_TEXTURES_SMALL = [
    # "nb_ursina/textures/sun03.png",
    # "nb_ursina/textures/earth.jpg",
    # "nb_ursina/textures/mercury.jpg",
    # "nb_ursina/textures/venus.jpg",
    # "nb_ursina/textures/mars.jpg",
    "nb_ursina/textures/pluto.jpg",
    "nb_ursina/textures/space/solar_system_scope/8k_earth_daymap.jpg",
    "nb_ursina/textures/space/solar_system_scope/8k_mercury.jpg",
    "nb_ursina/textures/space/solar_system_scope/4k_venus_atmosphere.jpg",
    "nb_ursina/textures/space/solar_system_scope/8k_mars.jpg",
    "nb_ursina/textures/arid/arid_01.png",
    "nb_ursina/textures/arid/arid_02.png",
    "nb_ursina/textures/arid/arid_03.png",
    "nb_ursina/textures/arid/arid_04.png",
    "nb_ursina/textures/arid/arid_05.png",
    "nb_ursina/textures/barren/barren_01.png",
    "nb_ursina/textures/barren/barren_02.png",
    "nb_ursina/textures/barren/barren_03.png",
    "nb_ursina/textures/barren/barren_04.png",
    "nb_ursina/textures/barren/barren_05.png",
    "nb_ursina/textures/dusty/dusty_01.png",
    "nb_ursina/textures/dusty/dusty_02.png",
    "nb_ursina/textures/dusty/dusty_03.png",
    "nb_ursina/textures/dusty/dusty_04.png",
    "nb_ursina/textures/dusty/dusty_05.png",
    "nb_ursina/textures/grassland/grassland_01.png",
    "nb_ursina/textures/grassland/grassland_02.png",
    "nb_ursina/textures/grassland/grassland_03.png",
    "nb_ursina/textures/grassland/grassland_04.png",
    "nb_ursina/textures/grassland/grassland_05.png",
    "nb_ursina/textures/jungle/jungle_01.png",
    "nb_ursina/textures/jungle/jungle_02.png",
    "nb_ursina/textures/jungle/jungle_03.png",
    "nb_ursina/textures/jungle/jungle_04.png",
    "nb_ursina/textures/jungle/jungle_05.png",
    "nb_ursina/textures/marshy/marshy_01.png",
    "nb_ursina/textures/marshy/marshy_02.png",
    "nb_ursina/textures/marshy/marshy_03.png",
    "nb_ursina/textures/marshy/marshy_04.png",
    "nb_ursina/textures/marshy/marshy_05.png",
    "nb_ursina/textures/martian/martian_01.png",
    "nb_ursina/textures/martian/martian_02.png",
    "nb_ursina/textures/martian/martian_03.png",
    "nb_ursina/textures/martian/martian_04.png",
    "nb_ursina/textures/martian/martian_05.png",
    "nb_ursina/textures/methane/methane_01.png",
    "nb_ursina/textures/methane/methane_02.png",
    "nb_ursina/textures/methane/methane_03.png",
    "nb_ursina/textures/methane/methane_04.png",
    "nb_ursina/textures/methane/methane_05.png",
    "nb_ursina/textures/sandy/sandy_01.png",
    "nb_ursina/textures/sandy/sandy_02.png",
    "nb_ursina/textures/sandy/sandy_03.png",
    "nb_ursina/textures/sandy/sandy_04.png",
    "nb_ursina/textures/sandy/sandy_05.png",
    "nb_ursina/textures/snowy/snowy_01.png",
    "nb_ursina/textures/snowy/snowy_02.png",
    "nb_ursina/textures/snowy/snowy_03.png",
    "nb_ursina/textures/snowy/snowy_04.png",
    "nb_ursina/textures/snowy/snowy_05.png",
    "nb_ursina/textures/tundra/tundra_01.png",
    "nb_ursina/textures/tundra/tundra_02.png",
    "nb_ursina/textures/tundra/tundra_03.png",
    "nb_ursina/textures/tundra/tundra_04.png",
    "nb_ursina/textures/tundra/tundra_05.png",
]
